# Davidson Example

In this small tutorial we will unroll the Davidson method to compute the lowest eigenvalue of a 5 x 5 matrix. The example is taken from the online presentation : http://www.esqc.org/static/lectures/Malmqvist_2B.pdf. The Davidson method can be summarized as:
  * Initialize : Define $n$ vectors $b = \{b_1,...b_n\}$
  * Iterate : loop untul convergence
    1. Orthogonalize the **b** vectors
    2. project the matrix on the subspace $A_p = b^T \times A \times b$
    3. Diagonalize the projected matrix : $A_p \times v = \lambda \times v$ 
    4. Compute the residue vector : $r = A\times b - \lambda \times b$
    5. Compute correction vector : $q = - r / (A_{ii} - \lambda)$
    6. Append the correction vector to $b$ : $b = \{b_1,...,b_n,q\}$ 

In [2]:
import numpy as np

**Define the matrix to diagonalize** : Let's define the matrix we want to diagonalize as :

In [3]:
A = 0.1*np.ones((5,5)) + np.diag([0.9,1.9,2.9,2.9,2.9])

In [4]:
print(A)

[[1.  0.1 0.1 0.1 0.1]
 [0.1 2.  0.1 0.1 0.1]
 [0.1 0.1 3.  0.1 0.1]
 [0.1 0.1 0.1 3.  0.1]
 [0.1 0.1 0.1 0.1 3. ]]


 **Intialization:** Our first guess for the lowest eigenstate is set to :

In [35]:
b = np.array([[1],[0],[0],[0],[0]]); print(b)

[[1]
 [0]
 [0]
 [0]
 [0]]


**FIRST ITERATION**

**1. Orthogonalization**: There is no need to orthogonalize the **b** vector

**2. Project A on the subspace** : $A_{p} = b^T \times A \times b$

In [17]:
ProjA = np.dot(b.T,np.dot(A,b)); print(ProjA)

[[1.]]


**3. Diagonalize the projected matrix** : Not needed here ...

In [19]:
l = 1.
v = [[1.]]

**4. Compute the residue vector** : $r = A\times b - \lambda \times b$

In [91]:
r = np.dot(A,b) - l*b; print(r)

[[0. ]
 [0.1]
 [0.1]
 [0.1]
 [0.1]]


**5. Compute correction vector** : $q = r/(A_{ii}-\lambda)$

In [92]:
q = - r.T / (np.diag(A)- l + 1E-18); q /= np.linalg.norm(q); print(q.T)

[[-0.        ]
 [-0.75592895]
 [-0.37796447]
 [-0.37796447]
 [-0.37796447]]


**SECOND ITERATION**

**1. Append the new vector to the old guesses and orthonormalize them**

In [93]:
b2 = np.hstack((b,q.T)); print(b2)

[[ 1.         -0.        ]
 [ 0.         -0.75592895]
 [ 0.         -0.37796447]
 [ 0.         -0.37796447]
 [ 0.         -0.37796447]]


In [94]:
b2,r = np.linalg.qr(b2); print(b2)

[[ 1.          0.        ]
 [-0.         -0.75592895]
 [-0.         -0.37796447]
 [-0.         -0.37796447]
 [-0.         -0.37796447]]


**2. Project A on the subspace** : $A_{p} = b^T \times A \times b$

In [86]:
ProjA = np.dot(b2.T,np.dot(A,b2)); print(ProjA)

[[ 1.   -0.2 ]
 [-0.2   3.05]]


**3. Diagonalize the projected matrix** :

In [87]:
theta,s = np.linalg.eigh(ProjA); print(theta)

[0.98067007 3.06932993]


**4. Compute the residue vector**

In [88]:
r2 = np.dot((np.dot(A,b2)-theta[0]*b2),s[:,0]); print(np.linalg.norm(r2))

0.04165641604351871


The norm of the reisdue is lower than the desired tolerance, therefore the calculations has converged !  
The approximate value of the eigenvalue is 0.979. The corresponding eigenvector is given by the corresponding Ritz vector

In [89]:
c = np.dot(b2,s[:,0]); print(c)

[-0.99536189  0.04810069  0.04810069  0.04810069  0.04810069]


We can compare those results with the numpy diagonalization

In [70]:
u,v = np.linalg.eigh(A); print(u[0], v[:,0])

0.9790664138520669 [ 0.99383078 -0.08532498 -0.04090648 -0.04090648 -0.04090648]
